name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.1 


        with:
          host: 52.66.243.186
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          passphrase: "Lekhraj@02"
          script: |
              export  PATH=$PATH:/home/ubuntu/.nvm/versions/node/v22.14.0/bin
              cd ci-cd
              git pull origin main
              npm install
              npm run build
              pm2 start npm --name "my-app" -- start


                                    
