name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10

        with:
          host: 52.66.243.186
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          passphrase: "Lekhraj@02"
          script: |
            cd ci-cd
            git pull origin main
            ls
script: |
  cd ci-cd
  git pull origin main
  /usr/bin/npm install
  /usr/bin/npm run build
  /usr/bin/npm run start

            
